name: 'SPDX License Checker'
description: 'Checks SPDX license headers in source files using check-copyright tool'

inputs:
  config_file:
    description: 'Path to the check_copyright_config.yaml file relative to repository root'
    required: false
    default: 'check_copyright_config.yaml'
  target_directory:
    description: 'Directory to check for SPDX headers (default: repository root)'
    required: false
    default: '.'
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.10'
  verbose:
    description: 'Enable verbose output'
    required: false
    default: 'true'
  dry_run:
    description: 'Run in dry-run mode (report issues without failing)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    
    - name: Install check-copyright tool
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install git+https://github.com/espressif/check-copyright.git@master
    
    - name: Check SPDX licenses
      shell: bash
      run: |
        VERBOSE_FLAG=""
        DRY_RUN_FLAG=""
        
        if [ "${{ inputs.verbose }}" = "true" ]; then
          VERBOSE_FLAG="--verbose"
        fi
        
        if [ "${{ inputs.dry_run }}" = "true" ]; then
          DRY_RUN_FLAG="--dry-run"
        fi
        
        python -m check_copyright $VERBOSE_FLAG $DRY_RUN_FLAG --config "${{ inputs.config_file }}" "${{ inputs.target_directory }}"
