# Example workflow for using the SPDX License Checker action
# 
# This file is for reference only - copy the relevant parts to your repository's
# .github/workflows directory and customize as needed.

name: Check SPDX Licenses

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - "main"
  merge_group:

jobs:
  check-spdx-licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check SPDX licenses
        uses: tenstorrent/tt-github-actions/.github/actions/spdx-checker@main
        with:
          config_file: './check_copyright_config.yaml'
          target_directory: '.'
          python_version: '3.10'
          verbose: 'true'
          dry_run: 'false'
