name: 'Get Job ID'
description: 'Fetches the job ID from GitHub API using the current job name, workflow ID and attempt ID'

inputs:
  job_name:
    description: 'Job name'
    default: '[1,2]'
  gh_token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}

outputs:
  job_id:
    description: 'The ID of the job'
    value: ${{ steps.fetch-job-id.outputs.job_id }}

runs:
  using: 'composite'
  steps:

  - name: Fetch Job ID
    id: fetch-job-id
    shell: bash
    run: |
      job_name="${{ inputs.job_name }}"
      workflow_id="${{ github.run_id }}"
      attempt_id="${{ github.run_attempt }}"
      response=$(curl -s -H "Authorization: token ${{ inputs.gh_token }}" \
        "https://api.github.com/repos/${{ github.repository }}/actions/runs/${workflow_id}/jobs")
      job_id=$(echo "$response" | jq -r '.jobs[] | select(.name | contains("${{ env.job-name }}")) | .id '))
      echo $job_id
      if ! [[ "$job_id" =~ ^[0-9]+$ ]]; then
        echo "Error: Job ID not found" >&2
        echo "$response"
        exit 1
      fi
      echo "job_id=$job_id" >> $GITHUB_OUTPUT
