name: 'Get Job ID'
description: 'Fetches the job ID from GitHub API using the current job name, workflow ID and attempt ID'

inputs:
  job_name:
    description: 'Job name'
    default: '[1,2]'
  gh_token:
    description: 'GitHub token'
    required: true

outputs:
  job_id:
    description: 'The ID of the job'
    value: ${{ steps.fetch-job-id.outputs.job_id }}

runs:
  using: 'composite'
  steps:

  # - name: Debug
  #   id: debug
  #   shell: bash
  #   run: |
  #     echo "github ${{ toJSON(github) }}"
  #     echo "github.job ${{ toJSON(github.job) }}"

  - name: Fetch Job ID
    id: fetch-job-id
    shell: bash
    run: |
      job_name="${{ github.job }}"
      workflow_id="${{ github.run_id }}"
      attempt_id="${{ github.run_attempt }}"
      response=$(curl -s -H "Authorization: token ${{ inputs.gh_token }}" \
        "https://api.github.com/repos/${{ github.repository }}/actions/runs/${workflow_id}/jobs")
      job_id=$(echo "$response" | jq -r --arg job_name "$job_name" '.jobs[] | select(.name == $job_name) | .id')
      echo $job_id
      echo "job_id=$job_id" >> $GITHUB_OUTPUT
