# .github/actions/execute-action/action.yml

name: "Collect data action"
description: "Collects data from a workflow run and uploads generated JSON to the SFTP server"
inputs:
  repository:
    description: "Repository name"
    required: true
  run_id:
    description: "Pipeline ID to use for data"
    required: true
  run_attempt:
    description: "Run attempt of the workflow run"
    required: true
  sftp_host:
    description: "SFTP server hostname (for cicd reports)"
    required: false
  sftp_user:
    description: "SFTP server username (for cicd reports)"
    required: false
  sftp_perf_host:
    description: "SFTP server hostname (for perf reports)"
    required: false
  sftp_perf_user:
    description: "SFTP server username (for perf reports)"
    required: false
  sftp_optest_host:
    description: "SFTP server hostname (for optest reports)"
    required: false
  sftp_optest_user:
    description: "SFTP server username (for optest reports)"
    required: false
  ssh-private-key:
    description: "SSH private key"
    required: false

runs:
  using: "composite"
  steps:

  - name: Collect workflow artifact and job logs
    shell: bash
    run: |
      ${GITHUB_ACTION_PATH}/download_workflow_data.sh ${{ inputs.repository }} ${{ inputs.run_id }} ${{ inputs.run_attempt }}

  - uses: actions/setup-python@v5
    with:
      python-version: '3.10'

  - name: Install dependencies
    shell: bash
    run: pip install -r ${GITHUB_ACTION_PATH}/requirements.txt

  - name: Create JSON
    env:
      PYTHONPATH: ${{ github.workspace }}
    shell: bash
    run: |
      python3 ${GITHUB_ACTION_PATH}/src/generate_data.py --run_id ${{ inputs.run_id }}
      # Workaround: Copy file to avoid GH upload filename limitations
      mkdir -p reports_json && cp *.json* reports_json/ && zip -rq reports_json.zip reports_json || true

  - name: Create key file
    if: ${{ inputs.ssh-private-key != '' }}
    shell: bash
    run: |
      echo "${{ inputs.ssh-private-key }}" > id_key
      chmod go-rwx id_key

  - name: Upload CICD reports
    if: ${{ inputs.sftp_host != '' }}
    shell: bash
    run: |
      sftp -oStrictHostKeyChecking=no -i id_key -b ${GITHUB_ACTION_PATH}/sftp-cicd.txt ${{ inputs.sftp_user }}@${{ inputs.sftp_host }}

  - name: Upload Perf reports
    if: ${{ inputs.sftp_perf_host != '' }}
    shell: bash
    run: |
      if compgen -G "benchmark_*.json*" > /dev/null; then
        sftp -oStrictHostKeyChecking=no -i id_key -b ${GITHUB_ACTION_PATH}/sftp-perf.txt ${{ inputs.sftp_perf_user }}@${{ inputs.sftp_perf_host }}
      else
        echo "No benchmark_*.json* files found. Skipping upload."
      fi

  - name: Upload OpTest reports
    if: ${{ inputs.sftp_optest_host != '' }}
    shell: bash
    run: |
      if compgen -G "github_job_*.json*" > /dev/null; then
        sftp -oStrictHostKeyChecking=no -i id_key -b ${GITHUB_ACTION_PATH}/sftp-optest.txt ${{ inputs.sftp_optest_user }}@${{ inputs.sftp_optest_host }}
      else
        echo "No github_job_*.json* files found. Skipping upload."
      fi

  - name: Upload workflow run data, even on failure
    if: ${{ !cancelled() }}
    uses: actions/upload-artifact@v4
    with:
      name: workflow-run-data
      path: |
        if-no-files-found: warn
        path: |
          reports_json.zip
          generated/cicd/${{ inputs.run_id }}/workflow.json
          generated/cicd/${{ inputs.run_id }}/workflow_jobs.json
